config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#logout'
  get 'admin' => 'admin#index'
  root 'top#index'

  # admin_menu
  namespace :admin do
    resources :articles
    resources :members
    resources :posts do
      resources :comments, only: %i[create destroy]
    end
    resources :players do
      resources :team_players
      collection do
        get 'player_import'
      end
    end
    resources :schedules
    resources :teams
  end
  resources :conferences
  resources :divisions
  resources :positions

  # general_menu
  resources :articles, only: %i[index show]
  resources :members do
    resources :posts, only: [:index]
  end
  resources :posts do
    resources :comments, only: %i[create destroy]
  end
  resources :players do
    resources :team_players, only: [:show]
  end
  resources :headcoaches
  resources :schedules, only: [:index]
  resources :teams
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :article_image, ArticleImageUploader

  belongs_to :member

  validates :title, presence: true, length: { minimum: 4, maximum: 40 }, uniqueness: true
  validates :body, presence: true, length: { minimum: 10, maximum: 2000 }
  validate :date_check

  def date_check
    errors.add(:expired_at, 'の日付を正しく記入してください。') unless released_at < expired_at
  end

  scope :public_article, -> do
    now = Time.now
    where('released_at <= ?', now).where('expired_at > ?', now).where(member_only: false)
  end

  scope :member_article, -> do
    now = Time.now
    where('released_at <= ?', now).where('expired_at > ?', now)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :member

  validates :body, presence: true, length: { maximum: 140 }
  validates :member_id, presence: true
  validates :post_id, presence: true
  validates :member_id, uniqueness: { message: 'すでにコメントが登録されています。', scope: [:post_id] }
end

app/models/conference.rb
class Conference < ApplicationRecord
  has_many :divisions
  has_many :teams, through: :divisions

  validates :conference_name, uniqueness: true

  def division_number
    Division.where('conference_id = ? ', id).count
  end

  def team_number
    Team.joins(division: :conference).where('conference_id = ?', id).count
  end
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :conference
  has_many :teams

  validates :conference_id, presence: true
  validates :division_name, presence: true, uniqueness: true
end

app/models/headcoach.rb
class Headcoach < ApplicationRecord
  mount_uploader :headcoach_image, HeadcoachImageUploader

  def full_name
    first_name + ' ' + last_name
  end

  def age
    date_format = '%Y%m%d'
    (Date.today.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10_000
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :posts
  has_many :comments

  validates :last_name, presence: true, length: { maximum: 6 }
  validates :first_name, presence: true, length: { maximum: 6 }
  validates :last_name_call, presence: true, length: { maximum: 10 }
  validates :first_name_call, presence: true, length: { maximum: 10 }
  validates :email, presence: true, uniqueness: true

  has_secure_password validations: true

  def password_correct
    errors.add(:password_confirmation, 'パスワードとパスワード（確認）が一致しません') unless password == password_confirmation
  end

  def full_name
    last_name + ' ' + first_name
  end

  def full_name_call
    last_name_call + ' ' + first_name_call
  end
end

app/models/player.rb
class Player < ApplicationRecord
  mount_uploader :player_image, PlayerImageUploader

  has_and_belongs_to_many :positions
  has_many :team_players

  def full_name
    first_name + ' ' + last_name
  end

  def age
    date_format = '%Y%m%d'
    (Date.today.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10_000
  end

  scope :current, -> do
    now = Time.now
    where('contract_start <= ?', now).where('contract_period > ?', now)
  end
end

app/models/position.rb
class Position < ApplicationRecord
  has_and_belongs_to_many :players
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
  has_many :comment

  validates :title, presence: true, length: { minimum: 4, maximum: 40 }
  validates :body, presence: true, length: { minimum: 10, maximum: 2000 }

  scope :open_post, -> do
    where(member_only: false)
  end

  scope :written_post, -> do
    where(member_id: @member)
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :home_team, class_name: 'Team', foreign_key: 'home_team_id'
  belongs_to :away_team, class_name: 'Team', foreign_key: 'away_team_id'
end

app/models/team.rb
class Team < ApplicationRecord
  mount_uploader :team_image, TeamImageUploader

  belongs_to :division
  has_many :team_players
  has_many :players, through: :team_players
  has_many :home_team_schedules, class_name: 'Schedule', foreign_key: 'home_team_id'
  has_many :away_team_schedules, class_name: 'Schedule', foreign_key: 'away_team_id'

  validates :division_id, presence: true
  validates :team_name, presence: true, uniqueness: true
  validates :establishment, presence: true
  validates :home_court, presence: true
  validates :owner, presence: true

  def current_player_number
    TeamPlayer.where('contract_start <= ?', Time.now).where('contract_period > ?', Time.now).where('team_id = ? ', id).count
  end

  def home_court_select
    home_court + ' <' + team_name + '>'
  end
end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :admin_member

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
    @teams = Team.all
  end

  def create
    @player = Player.new(player_params)
    @teams = Team.all
    if @player.save
      redirect_to @player
    else
      render 'new'
    end
  end

  def player_import; end

  def edit
    @player = Player.find(params[:id])
    @teams = Team.all
  end

  def show
    @player = Player.find(params[:id])
    @team_player = TeamPlayer.where(player_id: params[:id])
    @team = Team.find_by(id: :team_id)
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    if @player.save
      redirect_to @player
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      redirect_to :players
    else
      render 'edit'
    end
  end

  private

  def player_params
    params.require(:player).permit(
      :player_image,
      :first_name,
      :last_name,
      :number,
      :birthday,
      :height,
      :weight,
      :college,
      position_ids: []
    )
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
    @teams = Team.all
  end

  def create
    @player = Player.new(player_params)
    @teams = Team.all
    if @player.save
      redirect_to @player
    else
      render 'new'
    end
  end

  def edit
    @player = Player.find(params[:id])
    @teams = Team.all
  end

  def show
    @player = Player.find(params[:id])
    @team_player = TeamPlayer.where(player_id: params[:id])
    @team = Team.find_by(id: :team_id)
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    if @player.save
      redirect_to @player
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      redirect_to :players
    else
      render 'edit'
    end
  end

  private

  def player_params
    params.require(:player).permit(
      :player_image,
      :first_name,
      :last_name,
      :number,
      :birthday,
      :height,
      :weight,
      :college,
      position_ids: []
    )
  end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def posts_count
    @member = Member.find(params[:id])
    id = @member.id
    Post.where('member_id == ?', id).count
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/players/edit.html.erb
<% @page_title = t('page_action.edit', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<%= form_for @player do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<table>
  <tr>
    <th><%= f.label :player_image %></th>
    <td><%= f.file_field :player_image %></td>
  </tr>
  <tr>
    <th rowspan="2"><%= t('.name') %></th>
    <td><%= f.label :first_name %><%= f.text_field :first_name %></td>
  </tr>
  <tr>
    <td><%= f.label :last_name %><%= f.text_field :last_name %></td>
  </tr>
  <tr>
    <th><%= t('.number') %></th>
    <td><%= f.label :no %><%= f.text_field :number %></td>
  </tr>
  <tr>
    <th><%= f.label :position %></th>
    <td><%= f.collection_check_boxes(:position_ids, Position.all, :id, :position_name) %></td>
  </tr>
  <tr>
    <th><%= f.label :birthday %></th>
    <td><%= f.date_select :birthday, {
          start_year: 1970,
          end_year: Time.current.year,
          default: Time.zone.today - 30.year
        }
          %></td>
  </tr>
  <tr>
    <th><%= f.label :height %></th>
    <td><%= f.text_field :height  %></td>
  </tr>
  <tr>
    <th><%= f.label :weight %></th>
    <td><%= f.text_field :weight %></td>
  </tr>
  <tr>
    <th><%= f.label :country %></th>
    <td><%= f.country_select :country, priority_countries: ["US"] %></td>
  </tr>
  <tr>
    <th><%= f.label :college %></th>
    <td><%= f.text_field :college %></td>
  </tr>
</table>
<button><%= t('button.update') %></button>
<button><%= link_to t('button.delete'), @player, method: :delete, data: { confirm: '削除しますか?'} %></button>
<% end %>

app/views/admin/players/index.html.erb
<% @page_title = t('page_action.index', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<button type="button"><%= link_to t('page_action.new', name: Player.model_name.human), :new_player %></button>
<button type="button"><%= link_to t('.import'), :player_import_admin_players %></button>


<table>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.number') %></th>
    <th><%= t('.position') %></th>
    <th><%= t('.age') %></th>
    <th><%= t('.height') %></th>
    <th><%= t('.weight') %></th>
    <th><%= t('.college') %></th>
  </tr>
<% @players.each do |player| %>
  <tr>
    <td><%= link_to player.full_name, player %></td>
    <td><%= player.number %></td>
    <td><%= player.positions.sort.map(&:position_name).join('/') %></td>
    <td><%= player.age %></td>
    <td><%= player.height %></td>
    <td><%= player.weight %></td>
    <td><%= player.college %></td>
  </tr>
<% end %>
</table>

app/views/admin/players/new.html.erb
<% @page_title = t('page_action', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<%= form_for @player do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <table>
    <tr>
      <th><%= f.label :player_image %></th>
      <td><%= f.file_field :player_image %></td>
    </tr>
    <tr>
    <th rowspan="2"><%= t('.name') %></th>
      <td><%= f.label :first_name %><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td><%= f.label :last_name %><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <th><%= t('.number') %></th>
      <td><%= f.label :number %><%= f.text_field :number %></td>
    </tr>
    <tr>
      <th><%= f.label :position %></th>
      <td><%= f.collection_check_boxes(:position_ids, Position.all, :id, :position_name) %></td>
    </tr>
    <tr>
      <th><%= f.label :birthday %></th>
      <td><%= f.date_select :birthday, {
            start_year: 1970,
            end_year: Time.current.year,
            default: Time.zone.today - 30.year
          }
            %></td>
    </tr>
    <tr>
      <th><%= f.label :height %></th>
      <td><%= f.text_field :height  %></td>
    </tr>
    <tr>
      <th><%= f.label :weight %></th>
      <td><%= f.text_field :weight %></td>
    </tr>
    <tr>
      <th><%= f.label :country %></th>
      <td><%= f.country_select :country, priority_countries: ["US"] %></td>
    </tr>
    <tr>
      <th><%= f.label :college %></th>
      <td><%= f.text_field :college %></td>
    </tr>
  </table>
  <button><%= t('button.new', name: Player.model_name.human) %></button>
<% end %>

app/views/admin/players/player_import.html.erb
<% @page_title = t('.import') %>
<h1><%= @page_title %></h1>

<div>
  <%= form_tag players_path, method: :post, multipart: true do |f| %>
    <div>
      <%= text_field_tag 'filename',"", id: "filename", disabled: true %>
      <%= file_field_tag 'emails_file', id: "file_input", style: "display: none;", onchange: "file_selected($(this));" %>
      <%= button_tag t('file_select'), class: %i(btn-primary csv_input_btn), type: 'button', onclick: "$('#file_input').click();" %>
    </div>
    <div>
      <button type="submit"><%= t('.import') %></button>
    </div>
  <% end %>
</div>

app/views/admin/players/show.html.erb
<% @page_title = t('page_action.show', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<h2><%= t('.info') %></h2>
<%= image_tag @player.player_image.to_s, :size => '200x200' %>
<table>
  <tr>
    <th><%= t('.player') %></th>
    <td><%= @player.full_name %></td>
  </tr>
  <tr>
    <th><%= t('.number') %></th>
    <td><%= @player.number %></td>
  </tr>
  <tr>
    <th><%= t('.position') %></th>
    <td><%= @player.positions.sort.map(&:position_name).join('/') %></td>
  </tr>
  <tr>
    <th><%= t('.birthday') %></th>
    <td><%= @player.birthday.strftime("%Y年 %m月 %d日") %></td>
  </tr>
  <tr>
    <th><%= t('.height') %></th>
    <td><%= @player.height %></td>
  </tr>
  <tr>
    <th><%= t('.weight') %></th>
    <td><%= @player.weight %></td>
  </tr>
  <tr>
    <th><%= t('.college') %></th>
    <td><%= @player.college %></td>
  </tr>
</table>

<h2><%= t('.contract_info') %></h2>
<table>
  <tr>
    <th><%= t('.no') %></th>
    <th><%= t('.contract_team') %></th>
    <th><%= t('.contract_start') %></th>
    <th><%= t('.contract_period') %></th>
  </tr>
<% @team_player.each do |team_player| %>
  <tr>
    <td><%= link_to team_player.id, edit_admin_player_team_player_url(@player, team_player) %></td>
    <td><%= link_to team_player.team.team_name, team_path(team_player.team_id) %></td>
    <td><%= team_player.contract_start %></td>
    <td><%= team_player.contract_period %></td>
  </tr>
<% end %>
</table>

<button type="button"><%= link_to t('page_action.index', name: Player.model_name.human), :players %></button>

<% if admin_member %>
  <button type="button"><%= link_to t('button.new', name: Player.model_name.human), new_admin_player_team_player_url(@player) %></button>
  <button><%= link_to t('button.edit', name: Player.model_name.human), :edit_player %></button>
<% end %>

app/views/players/edit.html.erb
<% @page_title = t('page_action.edit', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<%= form_for @player do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<table>
  <tr>
    <th><%= f.label :player_image %></th>
    <td><%= f.file_field :player_image %></td>
  </tr>
  <tr>
    <th rowspan="2"><%= t('.name') %></th>
    <td><%= f.label :first_name %><%= f.text_field :first_name %></td>
  </tr>
  <tr>
    <td><%= f.label :last_name %><%= f.text_field :last_name %></td>
  </tr>
  <tr>
    <th><%= t('.number') %></th>
    <td><%= f.label :number %><%= f.text_field :number %></td>
  </tr>
  <tr>
    <th><%= f.label :position %></th>
    <td><%= f.collection_check_boxes(:position_ids, Position.all, :id, :position_name) %></td>
  </tr>
  <tr>
    <th><%= f.label :birthday %></th>
    <td><%= f.date_select :birthday, {
          start_year: 1970,
          end_year: Time.current.year,
          default: Time.zone.today - 30.year
        }
          %></td>
  </tr>
  <tr>
    <th><%= f.label :height %></th>
    <td><%= f.text_field :height  %></td>
  </tr>
  <tr>
    <th><%= f.label :weight %></th>
    <td><%= f.text_field :weight %></td>
  </tr>
  <tr>
    <th><%= f.label :country %></th>
    <td><%= f.country_select :country, priority_countries: ["US"] %></td>
  </tr>
  <tr>
    <th><%= f.label :college %></th>
    <td><%= f.text_field :college %></td>
  </tr>
</table>
<button><%= t('button.update') %></button>
<button><%= link_to t('button.delete'), @player, method: :delete, data: { confirm: '削除しますか？'} %></button>
<% end %>

app/views/players/index.html.erb
<% @page_title = t('page_action.index', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<% if admin_member %>
  <button type="button"><%= link_to t('page_action.new', name: Player.model_name.human), :new_player %></button>
<% end %>

<table>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.number') %></th>
    <th><%= t('.position') %></th>
    <th><%= t('.age') %></th>
    <th><%= t('.height') %></th>
    <th><%= t('.weight') %></th>
    <th><%= t('.college') %></th>
  </tr>
<% @players.each do |player| %>
  <tr>
    <td><%= link_to player.full_name, player %></td>
    <td><%= player.number %></td>
    <td><%= player.positions.sort.map(&:position_name).join('/') %></td>
    <td><%= player.age %></td>
    <td><%= player.height %></td>
    <td><%= player.weight %></td>
    <td><%= player.college %></td>
  </tr>
<% end %>
</table>

app/views/players/new.html.erb
<% @page_title = t('page_action.new', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<%= form_for @player do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
  <table>
    <tr>
      <th><%= f.label :player_image %></th>
      <td><%= f.file_field :player_image %></td>
    </tr>
    <tr>
    <th rowspan="2"><%= t('.name') %></th>
      <td><%= f.label :first_name %><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td><%= f.label :last_name %><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <th><%= t('.number') %></th>
      <td><%= f.label :number %><%= f.text_field :number %></td>
    </tr>
    <tr>
      <th><%= f.label :position %></th>
      <td><%= f.collection_check_boxes(:position_ids, Position.all, :id, :position_name) %></td>
    </tr>
    <tr>
      <th><%= f.label :birthday %></th>
      <td><%= f.date_select :birthday, {
            start_year: 1970,
            end_year: Time.current.year,
            default: Time.zone.today - 30.year
          }
            %></td>
    </tr>
    <tr>
      <th><%= f.label :height %></th>
      <td><%= f.text_field :height  %></td>
    </tr>
    <tr>
      <th><%= f.label :weight %></th>
      <td><%= f.text_field :weight %></td>
    </tr>
    <tr>
      <th><%= f.label :country %></th>
      <td><%= f.country_select :country, priority_countries: ["US"] %></td>
    </tr>
    <tr>
      <th><%= f.label :college %></th>
      <td><%= f.text_field :college %></td>
    </tr>
  </table>
  <button><%= t('button.new') %></button>
<% end %>

app/views/players/show.html.erb
<% @page_title = t('page_action.info', name: Player.model_name.human) %>
<h1><%= @page_title %></h1>

<h2><%= t('.info') %></h2>
<%= image_tag @player.player_image.to_s, :size => '200x200' %>
<table>
  <tr>
    <th><%= t('.name') %></th>
    <td><%= @player.full_name %></td>
  </tr>
  <tr>
    <th><%= t('.number') %></th>
    <td><%= @player.number %></td>
  </tr>
  <tr>
    <th><%= t('.position') %></th>
    <td><%= @player.positions.sort.map(&:position_name).join('/') %></td>
  </tr>
  <tr>
    <th><%= t('.birthday') %></th>
    <td><%= @player.birthday.strftime("%Y年 %m月 %d日") %></td>
  </tr>
  <tr>
    <th><%= t('.height') %></th>
    <td><%= @player.height %></td>
  </tr>
  <tr>
    <th><%= t('.weight') %></th>
    <td><%= @player.weight %></td>
  </tr>
  <tr>
    <th><%= t('.college') %></th>
    <td><%= @player.college %></td>
  </tr>
</table>

<h2><%= t('.contract_info') %></h2>
<table>
  <tr>
    <th><%= t('.num') %></th>
    <th><%= t('.contract_team') %></th>
    <th><%= t('.contract_start') %></th>
    <th><%= t('.contract_period') %></th>
  </tr>
<% @team_player.each_with_index do |team_player, idx| %>
  <tr>
    <td><%= link_to idx + 1, edit_admin_player_team_player_url(@player, team_player) %></td>
    <td><%= link_to team_player.team.team_name, team_path(team_player.team_id) %></td>
    <td><%= team_player.contract_start %></td>
    <td><%= team_player.contract_period %></td>
  </tr>
<% end %>
</table>

<button type="button"><%= link_to t('page_action.index', name: Player.model_name.human), :players %></button>

<% if admin_member %>
  <button type="button"><%= link_to t('page_action.new', name: TeamPlayer.model_name.human), new_admin_player_team_player_url(@player) %></button>
  <button><%= link_to t('button.edit'), :edit_player %></button>
<% end %>